package com.quant.trade.common.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 统一错误码枚举。
 * <p>
 * 每个错误码包含 code（字符串标识）和 description（中文描述），
 * 用于 BusinessException 携带结构化错误信息。
 */
@Getter
@AllArgsConstructor
public enum ErrorCodeEnum {

    SUCCESS("SUCCESS", "操作成功"),
    PARAM_ERROR("PARAM_ERROR", "参数错误"),
    VALIDATION_ERROR("VALIDATION_ERROR", "参数校验失败"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", "资源不存在"),
    DUPLICATE_RESOURCE("DUPLICATE_RESOURCE", "资源已存在，不可重复创建"),
    BUSINESS_RULE_VIOLATION("BUSINESS_RULE_VIOLATION", "违反业务规则"),
    INVALID_ENUM_CODE("INVALID_ENUM_CODE", "无效的枚举值"),
    RISK_CALCULATION_ERROR("RISK_CALCULATION_ERROR", "风控计算异常"),
    PORTFOLIO_CALCULATION_ERROR("PORTFOLIO_CALCULATION_ERROR", "持仓账本计算异常"),
    PRICE_SNAPSHOT_NOT_FOUND("PRICE_SNAPSHOT_NOT_FOUND", "当前价快照不存在"),
    INSUFFICIENT_HOLDING("INSUFFICIENT_HOLDING", "卖出数量超过持仓"),
    POSITION_SNAPSHOT_NOT_FOUND("POSITION_SNAPSHOT_NOT_FOUND", "持仓快照不存在"),
    POSITION_SNAPSHOT_NOT_EDITABLE("POSITION_SNAPSHOT_NOT_EDITABLE", "持仓快照不可编辑"),
    POSITION_SNAPSHOT_INVALID_TRANSITION("POSITION_SNAPSHOT_INVALID_TRANSITION", "持仓快照状态流转非法"),
    POSITION_SNAPSHOT_DUPLICATE_SYMBOL("POSITION_SNAPSHOT_DUPLICATE_SYMBOL", "持仓快照存在重复股票"),
    POSITION_SNAPSHOT_INVALID_ITEM("POSITION_SNAPSHOT_INVALID_ITEM", "持仓快照明细不合法"),
    TRADE_PLAN_NOT_FOUND("TRADE_PLAN_NOT_FOUND", "关联的交易计划不存在"),
    TRADE_PLAN_NOT_LINKABLE("TRADE_PLAN_NOT_LINKABLE", "交易计划已取消，不可关联"),
    TRADE_PLAN_SYMBOL_MISMATCH("TRADE_PLAN_SYMBOL_MISMATCH", "交易记录与计划的证券代码不一致"),
    JOURNAL_REFERENCED_BY_REVIEW("JOURNAL_REFERENCED_BY_REVIEW", "交易记录被复盘引用，不可删除"),
    POSITION_SNAPSHOT_COMPARISON_INVALID("POSITION_SNAPSHOT_COMPARISON_INVALID", "持仓快照对比参数非法"),
    STOCK_NOT_FOUND("STOCK_NOT_FOUND", "证券主数据不存在"),
    STOCK_ALREADY_EXISTS("STOCK_ALREADY_EXISTS", "证券主数据已存在"),
    INVALID_CANONICAL_SYMBOL("INVALID_CANONICAL_SYMBOL", "证券代码格式不合法"),
    SECURITY_VERIFICATION_FAILED("SECURITY_VERIFICATION_FAILED", "证券代码验证失败"),
    DAILY_BAR_CSV_PARSE_ERROR("DAILY_BAR_CSV_PARSE_ERROR", "CSV 解析失败"),
    DAILY_BAR_VALIDATION_ERROR("DAILY_BAR_VALIDATION_ERROR", "日 K 数据校验失败"),
    STOCK_HAS_DAILY_BARS("STOCK_HAS_DAILY_BARS", "证券存在日 K 数据，不可删除"),
    CSV_FILE_TOO_LARGE("CSV_FILE_TOO_LARGE", "CSV 文件超过大小限制"),
    CSV_TOO_MANY_ROWS("CSV_TOO_MANY_ROWS", "CSV 行数超过限制"),
    CSV_EMPTY_FILE("CSV_EMPTY_FILE", "CSV 文件为空"),
    CSV_WRONG_HEADER("CSV_WRONG_HEADER", "CSV 表头不匹配"),
    MARKET_DATA_PLAN_INVALID("MARKET_DATA_PLAN_INVALID", "行情采集计划配置不完整"),
    MARKET_DATA_PLAN_RUNNING("MARKET_DATA_PLAN_RUNNING", "行情采集计划正在执行"),
    MARKET_DATA_UNSUPPORTED_MARKET("MARKET_DATA_UNSUPPORTED_MARKET", "当前市场不支持该采集方式"),
    MARKET_DATA_PROVIDER_TIMEOUT("MARKET_DATA_PROVIDER_TIMEOUT", "行情数据源调用超时"),
    MARKET_DATA_PROVIDER_PERMISSION_DENIED("MARKET_DATA_PROVIDER_PERMISSION_DENIED", "行情数据源权限不足"),
    MARKET_DATA_PROVIDER_RATE_LIMITED("MARKET_DATA_PROVIDER_RATE_LIMITED", "行情数据源请求限流"),
    MARKET_DATA_EMPTY_RESULT("MARKET_DATA_EMPTY_RESULT", "行情数据源未返回数据"),
    MARKET_SECTOR_PROVIDER_UNAVAILABLE("MARKET_SECTOR_PROVIDER_UNAVAILABLE", "板块数据源不可用"),
    MARKET_DATA_RUN_RECOVERED("MARKET_DATA_RUN_RECOVERED", "服务重启后收敛遗留采集任务"),
    INTERNAL_ERROR("INTERNAL_ERROR", "系统内部错误");

    /** 错误码标识 */
    private final String code;

    /** 错误码中文描述 */
    private final String description;
}
